services:
  - type: web
    name: occw-quote-system
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install --only-binary=all -r requirements.txt"
    startCommand: "gunicorn --config gunicorn.conf.py app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PYTHONPATH
        value: "."
      - key: WEB_CONCURRENCY
        value: "1" 