services:
  - type: web
    name: occw-quote-system
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --only-binary=all Flask==2.3.3 pandas==2.0.3 numpy==1.24.3 PyPDF2==3.0.1 openpyxl==3.1.2"
    startCommand: "python app-basic.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PYTHONPATH
        value: "."
      - key: WEB_CONCURRENCY
        value: "1"
      - key: FORCE_REBUILD
        value: "true" 