services:
  - type: web
    name: 2020-occw-convertor
    env: python
    runtime: python-3.11.9
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn --config gunicorn.conf.py app:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123 