services:
  - type: web
    name: occw-quote-system
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install Flask==2.3.3 Werkzeug==2.3.7 PyPDF2==3.0.1 pandas==2.0.3 numpy==1.24.3 openpyxl==3.1.2 reportlab==4.0.4 python-dotenv==1.0.0 gunicorn==21.2.0
    startCommand: "python test-minimal.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PYTHONPATH
        value: "."
      - key: WEB_CONCURRENCY
        value: "1" 