services:
  - type: web
    name: occw-quote-system
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install Flask==2.3.3"
    startCommand: "python simple-test.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PYTHONPATH
        value: "."
      - key: WEB_CONCURRENCY
        value: "1" 